### ISSUE TITLE
Ping of nonexistant domain prints a stack trace

### ISSUE THREAD

**Issue by cjdelisle** [cjdelisle/cjdnstool#1]
```
notgay:cjdnstool user$ cjdnstool resolve irc.fc00 -v
Resolving irc.fc00
resolving irc.fc00 to ipv6
Error: Error: getaddrinfo ENOTFOUND irc.fc00
Error: NXDOMAIN
dgram.js:530
    throw new Error('Not running'); // error message from dgram_legacy.js
    ^

Error: Not running
    at Socket._healthCheck (dgram.js:530:11)
    at Socket.close (dgram.js:424:8)
    at Object.cjdns.disconnect (/Users/user/.nvm/versions/node/v6.5.0/lib/node_modules/cjdnstool/node_modules/cjdnsadmin/index.js:210:53)
    at nt (/Users/user/.nvm/versions/node/v6.5.0/lib/node_modules/cjdnstool/index.js:405:35)
    at Object.nThen (/Users/user/.nvm/versions/node/v6.5.0/lib/node_modules/cjdnstool/node_modules/nthen/index.js:37:21)
    at nThen (/Users/user/.nvm/versions/node/v6.5.0/lib/node_modules/cjdnstool/node_modules/nthen/index.js:67:16)
    at Object.disconnect (/Users/user/.nvm/versions/node/v6.5.0/lib/node_modules/cjdnstool/index.js:404:21)
    at cjdnstool.resolve (/Users/user/.nvm/versions/node/v6.5.0/lib/node_modules/cjdnstool/resolve.js:34:23)
    at nThen.nThen.nThen.nThen.nThen (/Users/user/.nvm/versions/node/v6.5.0/lib/node_modules/cjdnstool/index.js:298:13)
    at /Users/user/.nvm/versions/node/v6.5.0/lib/node_modules/cjdnstool/node_modules/nthen/index.js:25:30
notgay:cjdnstool user$
```

**Comment by cjdelisle** [comment]
fixed by fix of #2
